site_name: Digital Innovation Hub Miri SMA Launching - Integrated Project
site_description: Project documentation with Markdown.
site_author: All Aboard Young Leaders Center
repo_url: https://github.com/aaylc/integrated-projects-docs/
edit_uri: ""


dev_addr : localhost:8002

copyright: Copyright &copy; 2020 <a href="https://allaboardylc.org/">All Aboard Young Leaders </a>
